# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HxsKlyUhZzS2Exk-lkhPD7a4Qr91TyUQ
"""

import pandas as pd

data = pd.read_csv(r"/content/file.csv")

data

data.isnull()

data.isnull().sum()

data.drop(columns='country_name')

data



data.drop(columns='country_name',inplace=True)

data

data.head()

data[data.violation == "Speeding"]

data[data.violation == "Speeding"].driver_gender.value_counts()

data.head(200)

data.groupby('driver_gender').search_conducted.sum()

data.search_conducted.value_counts()

data.head()

data.stop_duration.value_counts()

data['stop_duration'] = data['stop_duration'].map({'0-15 Min' : 7.5 , '16-30 Min' :24 , '30+ Min' : 45})

data

data['stop_duration'].mean()

data.groupby('violation').driver_age.describe()